baseURL = "https://keen-swanson-bf10fd.netlify.com/"
languageCode = "en-us"
title = "Developer based in Lisbon Portugal"
sectionPage = "mainmenu"

[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = "10s"