name: Scheduled build
on:
  schedule:
    - cron: "5 * * * *"
jobs:
  build:
    steps:
      - name: Trigger our build webhook on Netlify
        run: curl -s -X POST "https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK_TOKEN }}"
        env:
          TOKEN: ${{ secrets.NETLIFY_CRON_JOB_TOKEN }}
